feat: add ERD
fursov231/java-filmorate pull request #3
Opened 2022-06-18 16:31 UTC by fursov231

2022-06-19 02:40 UTC, sergey-oreshkin requested changes
**отношение FILMS.mpa_id ->MPA.mpa_id**
- должно быть отношением многие-к-одному, то есть у одного МПА может быть много фильмов, один-к-оному значить что если закончатся свободные записи в МПА(а их всего 5) ты не сможешь больше создавать фильмы

**таблица FILM_GENRES**
- так же должна отражать отношение многие-ко-многим между фильмами и жанрами, вобщем должна быть такой же как с лайками

2022-06-19 08:57 UTC, sergey-oreshkin reviewed
**таблица FILM_GENRES**
- первичный ключ из одного поля _film_id_ не соответствует требованию уникальности, в таблице может быть несколько записей для одного фильма

2022-06-26 13:29 UTC, sergey-oreshkin reviewed
из прошлых ТЗ ограничения по длине login и name у User - 50 символов
названия фильма - 50 символов, описание фильма - 200 символов
в остальном замечаний нет

2022-06-26 20:41 UTC, TyutterinYakov reviewed
Добрый вечер! Отметил недочеты :) Хорошего вечера! Если возникнут вопросы - пиши в слак, буду рад помочь 🌚

2022-06-26 20:41 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return new ResponseEntity("Фильм успешно удален");
Отсутствует даймонд оператор

2022-06-26 20:41 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return new ResponseEntity("Неудачная попытка удаления фильма");
Отсутствует даймонд оператор

2022-06-26 20:41 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity delete(@PathVariable String name) {
Отсутствует дженерик для возвращаемого типа

2022-06-26 20:41 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity like(@PathVariable long filmId, @PathVariable long userId) {
Отсутствует дженерик для возвращаемого типа

2022-06-26 20:41 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ResponseEntity.java
> +public class ResponseEntity {
Есть готовый класс ResponseEntity, не нужно создавать его аналог)

2022-06-26 20:41 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity unlike(@PathVariable long filmId, @PathVariable long userId) {
Например, этот метод может выглядеть так)
    @PutMapping("/films/{filmId}/like/{userId}")
    public ResponseEntity<String> like(@PathVariable long filmId, @PathVariable long userId) {
        boolean isLike = filmService.like(filmId, userId);
        if (isLike) {
            return ResponseEntity.ok("Лайк успешно поставлен");
        } else {
            return new ResponseEntity<>("Неудачная попытка поставить лайк", HttpStatus.BAD_REQUEST);
        }
    }

2022-06-26 20:41 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      }
Аналогично и с этим контроллером. Следует исправить все методы, где используется ResponseEntity

2022-06-26 20:41 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Optional<Film> add(@RequestBody @Valid Film newFilm) {
не совсем понятна тактика использования типа Optional здесь)

2022-06-26 20:41 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Optional<User> findById(@PathVariable long id) {
не совсем понятна тактика использования типа Optional здесь)

2022-06-26 20:41 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/jdbc/JdbcFilmDao.java
> +public class JdbcFilmDao implements FilmStorage {
Для соблюдения принципов SOLID следует разбить хранилища еще на несколько: Friend, Like, Genre, Mpa

2022-06-26 20:41 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/jdbc/JdbcFilmDao.java
> +        } catch (NullPointerException e) {
обработка NPE является плохой практикой. Эту ошибку следует отнести к ошибкам валидации и проверять на уровне сервиса и выбрасывать исключение, если требуется

2022-06-26 20:41 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/jdbc/JdbcFilmDao.java
> +        } catch (NullPointerException e) {
обработка NPE является плохой практикой. Эту ошибку следует отнести к ошибкам валидации и проверять на уровне сервиса и выбрасывать исключение, если требуется

2022-06-26 20:41 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/jdbc/JdbcFilmDao.java
> +            return false;
можно просто выбросить непроверяемое исключение, которое обрабатывается в ErrorHandler со статусом 404 NOT_FOUND

2022-06-26 20:41 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/jdbc/JdbcFilmDao.java
> +            return false;
можно просто выбросить непроверяемое исключение, которое обрабатывается в ErrorHandler со статусом 404 NOT_FOUND

2022-06-27 23:53 UTC, TyutterinYakov approved these changes
Добрый вечер! Поздравляю с успешной сдачей спринта :) Сил и терпения на пути к цели! Продуктивной работы с командой!🌝  Доброй ночи!

2022-06-28 05:50 UTC, merged